"""
I have prepared simple examples of words that easily display how to pronounce a phoneme

words are in lower case with the letter(s) representing the phoneme in upper case
"""

phoneme_words = {
    "ˌɛ": [],
    "ð": [],
    "ˌʊ": [],
    "t": ["Tanks", "prompT", "inTake", "moTors", "daTE", "aTTempTed"],
    "ˌɑː": [],
    "aʊ": [],
    "eɪ": [],
    "ˈaɪ": [],
    "v": ["eVil", "surViVal", "motiVated", "Veto", "preView", "saVe"],
    "ˌeɪ": [],
    "ˌuː": [],
    "ɔɪ": [],
    "ˈʊ": [],
    "ˈæ": ["pAd", "adApters", "Acid", "Acts", "pAnda", "flAts"],
    "ˌəʊ": [],
    "k": ["aCt", "arK", "banK", "neCK", "identiCal", "Campaign"],
    "ˌɛə": [],
    "ˌɐ": [],
    "ʒ": [],
    "ɒ": [],
    "p": [],
    "ˌɔː": [],
    "ˈɔː": [],
    "m": ["huMble", "caMpus", "siMilar", "screaM", "MuseuM", "coMMiteMent"],
    "ˈiː": [],
    "ɹ": ["Royal", "pRinting", "Runner", "matRon", "aRRange", "Roll"],
    "ɑː": [],
    "ˌɪ": [],
    "əʊ": [],
    "n": ["News", "dowN", "titaN", "iNceNtive", "eNd", "iNNoceNt"],
    "h": [],
    "ˌɒ": [],
    "ɪ": [],
    "ɪə": [],
    "ŋ": [],
    "z": ["treeS", "froZen", "coneS", "eaSier", "haZe", "apologiSE"],
    "ˈɑː": [],
    "ˌaʊ": [],
    "ˈʊə": [],
    "ˌaɪ": [],
    "ˈaʊ": [],
    "ˈɪə": [],
    "ˈɜː": [],
    "ˌiː": [],
    "ˈə": ["cOs"],
    "ˌæ": [],
    "ˌʊə": [],
    "w": [],
    "l": ["fLeet", "Length", "rituaL", "Lions", "expLain", "gLee"],
    "i": ["hurrY", "heavY", "jointlY", "oilY", "lorrIEs", "worrIEs"],
    "ˈɐ": [],
    "ˈɪ": [],
    "ˈɔɪ": [],
    "ɔː": [],
    "ˌɪə": [],
    "ʃ": [],
    "ˈɒ": [],
    "aɪ": [],
    "ˈɛə": ["pAIR", "shAREd", "lAIR", "stAIRs", "flAIR", "cAring"],
    "ʊ": [],
    "ə": ["Allow", "syllabUs", "dreadfUl", "compressIOn", "marmAlade", "Amaze"],
    "b": ["laBor", "haBit", "Beetle", "Boy", "aBsent", "fiBre"],
    "uː": [],
    "ˈəʊ": [],
    "ɛə": [],
    "ˌɔɪ": [],
    "ˈuː": [],
    "æ": [],
    "ɛ": [],
    "g": [],
    "θ": [],
    "ʊə": [],
    "d": ["DefenDant", "Deter", "auDi", "enDorse", "blaDE", "finD"],
    "ɜː": [],
    "f": [],
    "ˌɜː": [],
    "ɐ": [],
    "iː": [],
    "dʒ": [],
    "s": ["Stop", "Sir", "graSp", "dentiStS", "laSt", "Cider"],
    "tʃ": [],
    "ˈɛ": [],
    "ˈeɪ": ["awAY", "lAke", "bAsed", "nAture", "okAY", "stAIn"],
    "j": [],
}
