"""
I have prepared simple examples of words that easily display how to pronounce a phoneme

words are in lower case with the letter(s) representing the phoneme in upper case
"""

phoneme_words = {
    "ˌɛ": ["tEchnological", "outlEt", "handhEld", "watershEd", "Entertain", "documEnted"],
    "ð": [],
    "ˌʊ": [],
    "t": ["Tanks", "prompT", "inTake", "moTors", "daTE", "aTTempTed"],
    "ˌɑː": [],
    "aʊ": [],
    "eɪ": [],
    "ˈaɪ": ["brIde", "Ivy", "vIral", "shY", "mIld", "prIce"],
    "v": ["eVil", "surViVal", "motiVated", "Veto", "preView", "saVe"],
    "ˌeɪ": ["donAte", "fAce", "calculAte", "overtAke", "anywAY", "operAte"],
    "ˌuː": ["bathrOOms", "andrEWs", "constitUte", "revenUEs", "intervIEWs", "residUE"],
    "ɔɪ": [],
    "ˈʊ": [],
    "ˈæ": ["pAd", "adApters", "Acid", "Acts", "pAnda", "flAts"],
    "ˌəʊ": [],
    "k": ["aCt", "arK", "banK", "neCK", "identiCal", "Campaign"],
    "ˌɛə": [],
    "ˌɐ": [],
    "ʒ": [],
    "ɒ": [],
    "p": ["keePer", "PoPs", "Pouch", "jumPing", "Plain", "lifesPan"],
    "ˌɔː": [],
    "ˈɔː": ["crAWl", "cAll", "accOrd", "awArd", "scOre", "fOUGHt"],
    "m": ["huMble", "caMpus", "siMilar", "screaM", "MuseuM", "coMMiteMent"],
    "ˈiː": ["tEEnagers", "retrIEve", "fEE", "hEAted", "frEEly", "Equal"],
    "ɹ": ["Royal", "pRinting", "Runner", "matRon", "aRRange", "Roll"],
    "ɑː": [],
    "ˌɪ": [],
    "əʊ": [],
    "n": ["News", "dowN", "titaN", "iNceNtive", "eNd", "iNNoceNt"],
    "h": ["Hand", "Hat", "inHerit", "withHold", "Holiday", "Help"],
    "ˌɒ": ["icOn", "laptOp", "ecOmmerce", "Opportunities", "Obligations", "lOllipop", "pokemOn"],
    "ɪ": ["Incur", "InevItable", "chIswIck", "sayIng", "antIcs", "dIsrupt"],
    "ɪə": ["omniscIEnt", "latvIA", "victorIA", "warrIORs", "socIOlogical", "idIOm"],
    "ŋ": ["duriNG", "daNk", "kiNGs", "haNG", "stiNk", "aloNG"],
    "z": ["treeS", "froZen", "coneS", "eaSier", "haZe", "apologiSE"],
    "ˈɑː": [],
    "ˌaʊ": [],
    "ˈʊə": [],
    "ˌaɪ": [],
    "ˈaʊ": ["hOUseholds", "encOUnter", "vOwel", "pOWer", "lOUd", "OUtlook"],
    "ˈɪə": [],
    "ˈɜː": ["gIRl", "tERm", "squIRt", "fIRstly", "bURgers", "EARlier"],
    "ˌiː": [],
    "ˈə": ["cOs"],
    "ˌæ": ["cAscade", "formAt", "Animation", "meerkAt", "progrAm", "grandAd"],
    "ˌʊə": [],
    "w": [],
    "l": ["fLeet", "Length", "rituaL", "Lions", "expLain", "gLee"],
    "i": ["hurrY", "heavY", "jointlY", "oilY", "lorrIEs", "worrIEs"],
    "ˈɐ": ["sUnset", "dUcks", "pUmps", "rUgged", "Ultimate", "plUg"],
    "ˈɪ": ["twItch", "bIll", "sYmmetry", "zIp", "pIxels", "Injured"],
    "ˈɔɪ": [],
    "ɔː": [],
    "ˌɪə": [],
    "ʃ": ["SHy", "muSHrooms", "accompliSH", "raTios", "perfecTIon", "miSSions"],
    "ˈɒ": ["blOgging", "hydrAUlic", "swOt", "blOcked", "dOt", "pOnd"],
    "aɪ": [],
    "ˈɛə": ["pAIR", "shAREd", "lAIR", "stAIRs", "flAIR", "cAring"],
    "ʊ": [],
    "ə": ["Allow", "syllabUs", "dreadfUl", "compressIOn", "marmAlade", "Amaze"],
    "b": ["laBor", "haBit", "Beetle", "Boy", "aBsent", "fiBre"],
    "uː": [],
    "ˈəʊ": ["sOAp", "lOAthe", "blOke", "relOAd", "rOAst", "Overall"],
    "ɛə": [],
    "ˌɔɪ": [],
    "ˈuː": ["glUE", "tOOth", "flEW", "sEWer", "bOO", "dOing"],
    "æ": ["Ambitious", "shAmpoo", "Advert", "mAgnetic", "webcAm", "decAff"],
    "ɛ": ["spEctator", "cortEx", "intEl", "gEneralise", "Enroll", "Embed"],
    "g": [],
    "θ": [],
    "ʊə": [],
    "d": ["DefenDant", "Deter", "auDi", "enDorse", "blaDE", "finD"],
    "ɜː": [],
    "f": [],
    "ˌɜː": [],
    "ɐ": [],
    "iː": [],
    "dʒ": ["briDGE", "cabbaGE", "maGic", "synerGy", "Jealousy", "clerGy"],
    "s": ["Stop", "Sir", "graSp", "dentiStS", "laSt", "Cider"],
    "tʃ": [],
    "ˈɛ": ["sEmi", "Eggs", "affEcted", "Enter", "bEtter", "amEnded"],
    "ˈeɪ": ["awAY", "lAke", "bAsed", "nAture", "okAY", "stAIn"],
    "j": ["CUte", "MUsic", "TUne", "Yen", "Yoke", "Yes", "evalUating", "Fuse"],
}
# TODO: note on frontend that "j" is the "yer" sound
